"use client";
import { useMemo, useState } from "react";
import { directions, generateMap, Hex, keyOf, passable, reveal, terrainNames } from "../lib/game";

type View="home"|"auth"|"rules"|"cabinet"|"lobby"|"game";
const rooms=[
  {name:"Експедиція #014",players:"3 / 6",map:"Середня",time:"60 с",status:"Очікує гравців"},
  {name:"Тиха затока #009",players:"5 / 6",map:"Велика",time:"90 с",status:"Очікує гравців"},
  {name:"Чорний приплив #007",players:"4 / 4",map:"Середня",time:"Раунд 8",status:"Гра триває"},
];
const mockEvents=["десь далеко почувся дивний звук.","вітер раптово змінив напрямок.","цього разу нічого не сталося. Підозріло.","земля під ногами ледь помітно здригнулася."];

export default function Home(){
 const [view,setView]=useState<View>("home"); const [authed,setAuthed]=useState(false); const [spectator,setSpectator]=useState(false);
 const [config,setConfig]=useState({size:"Середня",time:"60 секунд",fog:true,max:6,visibility:"Відкрита",flood:"Стандартне"});
 const nav=(v:View)=>setView(v);
 return <main className={view==="game"?"game-shell":"site-shell"}>
  {view!=="game"&&<Header authed={authed} nav={nav} logout={()=>{setAuthed(false);nav("home")}}/>}
  {view==="home"&&<Start nav={nav} authed={authed} config={config} setConfig={setConfig} watch={()=>{setSpectator(true);nav("game")}}/>}
  {view==="auth"&&<Auth onDone={()=>{setAuthed(true);nav("home")}}/>}
  {view==="rules"&&<Rules/>}{view==="cabinet"&&<Cabinet/>}
  {view==="lobby"&&<Lobby config={config} leave={()=>nav("home")} start={()=>{setSpectator(false);nav("game")}}/>}
  {view==="game"&&<Game spectator={spectator} size={config.size} leave={()=>nav("home")}/>} 
 </main>
}

function Header({authed,nav,logout}:{authed:boolean;nav:(v:View)=>void;logout:()=>void}){return <header className="header"><button className="logo" onClick={()=>nav("home")}><span>ТАК</span> СТАЛОСЬ<i>•</i></button><nav><button onClick={()=>nav("rules")}>Правила гри</button>{authed?<><button onClick={()=>nav("cabinet")}>Кабінет</button><button onClick={logout}>Вихід</button></>:<button className="nav-accent" onClick={()=>nav("auth")}>Вхід</button>}</nav></header>}

function Start({nav,authed,config,setConfig,watch}:any){return <div className="home-wrap"><section className="hero"><div><p className="eyebrow">Виживання · Дослідження · Тактика</p><h1>Світ не пояснює.<br/><em>Він просто стається.</em></h1></div><p>Збирайте експедицію, відкривайте невідомі землі й витрачайте кожну дію так, ніби вона остання.</p></section><div className="home-grid"><section><div className="section-head"><div><p className="eyebrow">Відкриті кімнати</p><h2>Доступні ігри</h2></div><span className="online"><i/> 12 онлайн</span></div><div className="room-list">{rooms.map((r,i)=><article className="room" key={r.name}><div className="room-mark">0{i+7}</div><div><h3>{r.name}</h3><p>{r.players} гравців <b>·</b> {r.map} карта <b>·</b> {r.time}</p></div><span className={r.status.includes("триває")?"status live":"status"}>{r.status}</span><button onClick={()=>r.status.includes("триває")?watch():nav("lobby")}>{r.status.includes("триває")?"Слідкувати":"Доєднатися"} <b>→</b></button></article>)}</div></section><aside className="create"><p className="eyebrow">Нова експедиція</p><h2>Створити гру</h2><label>Розмір карти<select value={config.size} onChange={e=>setConfig({...config,size:e.target.value})}><option>Маленька</option><option>Середня</option><option>Велика</option></select></label><div className="form-row"><label>Час ходу<select value={config.time} onChange={e=>setConfig({...config,time:e.target.value})}><option>30 секунд</option><option>60 секунд</option><option>90 секунд</option><option>Без обмеження</option></select></label><label>Гравців<select value={config.max} onChange={e=>setConfig({...config,max:+e.target.value})}>{[2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label></div><label className="switch-row"><span><b>Туман війни</b><small>Світ прихований до дослідження</small></span><input type="checkbox" checked={config.fog} onChange={e=>setConfig({...config,fog:e.target.checked})}/></label><label>Видимість<select value={config.visibility} onChange={e=>setConfig({...config,visibility:e.target.value})}><option>Відкрита</option><option>Приватна</option></select></label><label>Швидкість затоплення<select value={config.flood} onChange={e=>setConfig({...config,flood:e.target.value})}><option>Повільне</option><option>Стандартне</option><option>Швидке</option></select></label><button className="primary" onClick={()=>authed?nav("lobby"):nav("auth")}>СТВОРИТИ ГРУ <span>↗</span></button></aside></div></div>}

function Auth({onDone}:{onDone:()=>void}){const [tab,setTab]=useState("Вхід");return <section className="center-page"><div className="auth-card"><p className="eyebrow">Доступ до експедиції</p><h1>{tab}</h1><div className="tabs"><button className={tab==="Вхід"?"active":""} onClick={()=>setTab("Вхід")}>Вхід</button><button className={tab==="Реєстрація"?"active":""} onClick={()=>setTab("Реєстрація")}>Реєстрація</button></div>{tab==="Реєстрація"&&<label>Ім’я гравця<input placeholder="Ваш позивний"/></label>}<label>Електронна пошта<input type="email" placeholder="name@example.com"/></label><label>Пароль<input type="password" placeholder="••••••••"/></label><button className="primary" onClick={onDone}>{tab.toUpperCase()} <span>→</span></button><p className="hint">Безпечна авторизація підготовлена через окремий проєкт Supabase «tak-stalos».</p></div></section>}
function Rules(){return <section className="reading"><p className="eyebrow">Версія правил 0.1</p><h1>Як вижити у невідомому</h1><div className="rule-grid">{[["01","Три дії","Кожен хід ви отримуєте 3 очки дій. Рух і дослідження коштують по 1 AP."],["02","Шість напрямків","Пересувайтеся лише на сусідні гекси. Вода, скелі та лава непрохідні."],["03","Туман війни","Ви бачите свій гекс і сусідні. Відкрита земля залишається на карті як спогад."],["04","Ваше рішення","Завершити хід можна будь-коли — навіть якщо залишилися очки дій."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="notice">Бойові системи, монстри, пастки, магазини та затоплення ще перебувають у розробці.</div></section>}
function Cabinet(){const stats=[["Ігор","27"],["Перемог","8"],["Вижив","14"],["Відкрито тайлів","1 842"],["Монстрів","0"],["Гравців","0"],["Здобуто золота","6 420"],["Монет","310"]];return <section className="reading"><p className="eyebrow">Особова справа</p><div className="profile-head"><div className="avatar">P</div><div><h1>Мандрівник Pas</h1><p>Експедиційний ранг: Шукач</p></div></div><div className="stats">{stats.map(s=><article key={s[0]}><b>{s[1]}</b><span>{s[0]}</span></article>)}</div><h2>Останні експедиції</h2><div className="history"><p>Чорний приплив #007 <span>Раунд 8 · триває</span></p><p>Зелена межа #003 <span>Вижив · 42 тайли</span></p></div></section>}

function Lobby({config,leave,start}:any){const [ready,setReady]=useState(false);return <section className="reading lobby"><p className="eyebrow">Кімната очікування</p><div className="lobby-head"><div><h1>Експедиція #015</h1><p>Господар: Мандрівник Pas</p></div><span className="code">КОД: TS-8412</span></div><div className="lobby-grid"><div><h2>Учасники</h2>{["Мандрівник Pas","Max","Iryna"].map((p,i)=><div className="player-row" key={p}><span className="mini-avatar">{p[0]}</span><b>{p}</b><small className={i===0&&ready?"ready":""}>{i===0?(ready?"Готовий":"Не готовий"):i===1?"Готовий":"Не готовий"}</small></div>)}{Array.from({length:config.max-3}).map((_,i)=><div className="player-row empty" key={i}><span className="mini-avatar">+</span><b>Вільне місце</b></div>)}</div><aside className="settings"><h2>Параметри</h2><p><span>Карта</span><b>{config.size}</b></p><p><span>Туман війни</span><b>{config.fog?"Увімкнено":"Вимкнено"}</b></p><p><span>Час ходу</span><b>{config.time}</b></p><p><span>Гравців</span><b>3 / {config.max}</b></p><p><span>Затоплення</span><b>{config.flood}</b></p></aside></div><div className="lobby-actions"><button className="ghost" onClick={leave}>Вийти з кімнати</button><button className="secondary" onClick={()=>setReady(!ready)}>{ready?"НЕ ГОТОВИЙ":"ГОТОВИЙ"}</button><button className="primary" onClick={start}>ПОЧАТИ ГРУ <span>→</span></button></div></section>}

function Game({spectator,size,leave}:{spectator:boolean;size:string;leave:()=>void}){
 const radius=size==="Маленька"?4:size==="Велика"?7:5; const discovered=useMemo(()=>new Set<string>(),[]);
 const initial=useMemo(()=>{let m=generateMap(radius);const spawn=m.filter(t=>passable(t.terrain))[Math.floor(Math.random()*m.filter(t=>passable(t.terrain)).length)];return {m:reveal(m,spawn,1,discovered),p:{q:spawn.q,r:spawn.r}}},[]);
 const [map,setMap]=useState<Hex[]>(initial.m);const [pos,setPos]=useState(initial.p);const [ap,setAp]=useState(3);const [round,setRound]=useState(1);const [mode,setMode]=useState<"none"|"move">("none");const [left,setLeft]=useState(false);const [right,setRight]=useState(false);const [events,setEvents]=useState(["Ви прокинулися посеред невідомої землі.","Так Сталось... десь далеко почувся дивний звук."]); 
 const valid=new Set(directions.map(([dq,dr])=>keyOf(pos.q+dq,pos.r+dr)).filter(k=>map.some(t=>keyOf(t.q,t.r)===k&&passable(t.terrain))));
 const actMove=(t:Hex)=>{if(spectator||mode!=="move"||ap<1||!valid.has(keyOf(t.q,t.r)))return;const next={q:t.q,r:t.r};setPos(next);setAp(ap-1);setMap(reveal(map,next,1,discovered));setEvents(e=>["Ви перемістилися на новий тайл.",...e]);setMode("none")};
 const explore=()=>{if(spectator||ap<1)return;setAp(ap-1);setMap(reveal(map,pos,2,discovered));setEvents(e=>["Ви уважно дослідили околиці.",...e])};
 const endTurn=()=>{if(spectator)return;setRound(round+1);setAp(3);setMode("none");setMap(reveal(map,pos,1,discovered));setEvents(e=>[`Так Сталось... ${mockEvents[round%mockEvents.length]}`,...e])};
 const W=54,H=47; const coords=map.map(t=>({...t,x:(t.q+radius)*W+(t.r+radius)*W/2+80,y:(t.r+radius)*H+45})); const maxX=Math.max(...coords.map(t=>t.x))+90,maxY=Math.max(...coords.map(t=>t.y))+80;
 return <div className="game"><div className="game-top"><button className="game-logo" onClick={leave}>TS</button><Pocket side="Ліва кишеня" open={left} toggle={()=>setLeft(!left)} items={["Старий ніж","Їжа","Капкан"]}/><div className="statusbar"><span>♥ <b>10 / 10</b></span><span>◉ <b>120</b></span><span>◆ <b>2</b></span><span>▰ <b>4</b></span><span>● <b>3</b></span></div><div className="turn"><small>{spectator?"СПОСТЕРЕЖЕННЯ":"ВАШ ХІД"}</small><b>Раунд {round}</b><span>00:{String(60-round*3).padStart(2,"0")}</span></div><Pocket side="Права кишеня" open={right} toggle={()=>setRight(!right)} items={["Аптечка","Порожньо","Порожньо"]}/></div>
 <div className="map-viewport"><div className="mist mist-a"/><div className="mist mist-b"/><svg className="hexmap" viewBox={`0 0 ${maxX} ${maxY}`} preserveAspectRatio="xMidYMid meet">{coords.map(t=>{const points=Array.from({length:6},(_,i)=>{const a=Math.PI/180*(60*i);return `${t.x+29*Math.cos(a)},${t.y+29*Math.sin(a)}`}).join(" ");const k=keyOf(t.q,t.r);return <g key={k} className={`tile ${t.visible} terrain-${t.terrain} ${mode==="move"&&valid.has(k)?"valid":""}`} onClick={()=>actMove(t)}><polygon points={points}/>{t.visible!=="unknown"&&<text x={t.x} y={t.y+4}>{terrainNames[t.terrain].slice(0,1)}</text>}{pos.q===t.q&&pos.r===t.r&&<g className="token"><circle cx={t.x} cy={t.y} r="13"/><circle cx={t.x} cy={t.y} r="7"/><path d={`M${t.x-5},${t.y+1} L${t.x},${t.y-7} L${t.x+5},${t.y+1} Z`}/></g>}</g>})}</svg><div className="legend"><span><i className="l-forest"/> Ліс</span><span><i className="l-grass"/> Трава</span><span><i className="l-desert"/> Пустеля</span><span><i className="l-water"/> Вода</span><span><i className="l-rock"/> Скелі</span><span><i className="l-lava"/> Лава</span></div></div>
 {!spectator&&<aside className="actions"><p>ОЧКИ ДІЙ <b>{[0,1,2].map(i=><i key={i} className={i<ap?"on":""}/>)}</b></p><button className={mode==="move"?"selected":""} onClick={()=>ap&&setMode(mode==="move"?"none":"move")}><span>↗</span><b>Переміститися</b><small>1 AP</small></button><button disabled><span>⚔</span><b>Атакувати</b><small>Скоро</small></button><button onClick={explore} disabled={!ap}><span>⌖</span><b>Дослідити</b><small>1 AP</small></button><button disabled><span>◇</span><b>Розмістити</b><small>Скоро</small></button><button className="end" onClick={endTurn}>ЗАВЕРШИТИ ХІД</button></aside>}
 <div className="console"><div className="console-title"><b>ЖУРНАЛ ПОДІЙ</b><span>● СИСТЕМА</span></div><div className="messages">{events.slice(0,4).map((e,i)=><p key={i} className={e.startsWith("Так Сталось")?"fate":""}><small>{i?"СИСТЕМА":"ЗАРАЗ"}</small>{e.startsWith("Так Сталось")?<><strong>ТАК СТАЛОСЬ...</strong>{e.replace("Так Сталось...","")}</>:e}</p>)}</div></div>{spectator&&<div className="spectator-badge">РЕЖИМ СПОСТЕРІГАЧА · ДІЇ ВИМКНЕНО <button onClick={leave}>Вийти</button></div>}</div>
}
function Pocket({side,open,toggle,items}:{side:string;open:boolean;toggle:()=>void;items:string[]}){return <div className="pocket-wrap"><button className="pocket" onClick={toggle}><span>▱</span><small>{side}</small><b>{items.filter(x=>x!=="Порожньо").length} / 3</b></button>{open&&<div className="inventory"><h3>{side}</h3>{items.map((x,i)=><p className={x==="Порожньо"?"empty":""} key={i}><i>{x==="Порожньо"?"＋":"◆"}</i>{x}</p>)}</div>}</div>}
